name: Docker Image CI
env:
      TOKEN: ${{ secrets.DOCKERHUB }}

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tex8503/zpl-rest:main;docker login -u tex8503 -p ${{ env.TOKEN }};docker push tex8503/zpl-rest:main
